[package]

name = "ftp"
version = "0.0.2"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>"]
repository = "https://github.com/mattnenterprise/rust-ftp"
description = "FTP client for Rust"
readme = "README.md"
license = "MIT"


[lib]
name ="ftp"
path = "src/ftp.rs"

[[bin]]
name = "example"
path = "example.rs"