[package]

name = "ftp"
version = "0.0.7"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>"]
repository = "https://github.com/mattnenterprise/rust-ftp"
description = "FTP client for Rust"
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
regex = "*"

[lib]
name ="ftp"
path = "src/ftp.rs"
