[package]

name = "ftp"
version = "0.0.7"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>"]
repository = "https://github.com/mattnenterprise/rust-ftp"
description = "FTP client for Rust"
readme = "README.md"
license = "MIT OR Apache-2.0"

[lib]
name ="ftp"
path = "src/lib.rs"

[features]
secure = ["openssl"]

[dependencies]
lazy_static = "0.1"
regex = "0.1"
chrono = "0.2"

[dependencies.openssl]
version = "0.7"
optional = true
